#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="spacemacs.css">

#+TITLE: Descubriendo el Desarrollo Web As칤ncrono en PHP: Una Aventura de Aprendizaje 游

* El Comienzo de la Aventura

Como desarrollador PHP, siempre estoy buscando  o aprendiendo cosas que me parecen interesantes. A lo largo de mi carrera, a menudo me he sentido frustrado por la complejidad innecesaria de muchos frameworks, deseando encontrar una manera de enfocarme en resolver problemas reales, en lugar de luchar contra las herramientas.

Mi curiosidad se aviv칩 a칰n m치s con la reciente actualizaci칩n del framework Symfony, que introdujo la posibilidad de cambiar los "runtimes", permitiendo opciones como la ejecuci칩n as칤ncrona. Esto me impuls칩 a investigar m치s a fondo.

* Descubriendo RxPHP y la Programaci칩n Reactiva

En un momento de mi carrera me vi metido en el desarrollo de un front , para el cual el gran Guillermo Cuenca me introdujo en el mundo de la programaci칩n reactiva con JS y descubr칤 su potencial.
 Tras pasar un tiempo me top칠 con los videos de [[https://www.youtube.com/watch?v=mJFbYHYxSDg][Sergey Zhuk]] sobre RxPHP y la programaci칩n reactiva. Estos conceptos me fascinaron y comenc칠 a explorar m치s a fondo.
Recursos como [[https://rxmarbles.com/][RxMarbles]] y [[https://reactivex.io/learnrx/][LearnRx]] me ayudaron a comprender mejor los principios de la programaci칩n reactiva y c칩mo podr칤a aplicarlos en PHP.
 Ser칤a posible aplicar estos conceptos en PHP? Me pregunt칠.


Vi el potencial de crear aplicaciones web altamente eficientes y receptivas aprovechando la naturaleza as칤ncrona de PHP. Sin embargo, not칠 que no hab칤a muchas opciones para comenzar f치cilmente con estas tecnolog칤as en PHP sin tener que configurar todo desde cero.

* Creando una Soluci칩n

Inspirado por este desaf칤o, decid칤 crear [[https://github.com/pascualmg/cohete][un microframework]] que combinara la programaci칩n as칤ncrona con el Dise침o Guiado por el Dominio para Desarrolladores (DDDD).
Aunque esta 칰ltima parte , es meramente organizativa y nada tiene que ver con el core , que est치 totalmente separado.

Mi objetivo era proporcionar una manera f치cil para que los programadores de backend en PHP pudieran comenzar a utilizar estas tecnolog칤as sin tener que preocuparse por la configuraci칩n inicial.

Una de las grandes ventajas de este microframework es que el c칩digo del n칰cleo es super sencillo. Esto te da un control casi total sobre el c칩digo de tu framework y facilita su comprensi칩n y extensi칩n.

Adem치s, es poco opinionado y se puede ampliar f치cilmente seg칰n tus necesidades. Incluso puedes construir tu propio kernel desde cero si lo deseas f치cilmente.

* Un Vistazo al C칩digo

Veamos un ejemplo pr치ctico. Imaginemos que queremos crear un endpoint para publicar un nuevo post en un blog.

Primero, definimos la ruta en nuestro archivo de configuraci칩n:

#+BEGIN_SRC json
[
  {
    "method": "POST",
    "path": "/post",
    "handler": "\\CreatePostController"
  }
]
#+END_SRC

Luego, implementamos el =CreatePostController=:

#+BEGIN_SRC php
class CreatePostController implements HttpRequestHandler
{
    public function __invoke(ServerRequestInterface $request): PromiseInterface
    {
        $payload = json_decode($request->getBody()->getContents(), true);

        $post = new Post(
            Uuid::from($payload['id']),
            $payload['title'],
            $payload['content']
        );

        return $this->postRepository->save($post)->then(
            fn() => JsonResponse::created(),
            fn(Exception $e) => JsonResponse::withError($e)
        );
    }
}
#+END_SRC

Aqu칤 es donde brilla la magia de ReactPHP. El m칠todo =save= del repositorio devuelve una =Promise=. Si el post se guarda con 칠xito, la promesa se resuelve, y si algo sale mal, se rechaza.

Lo fascinante es que, mientras se resuelve la promesa, el servidor puede continuar procesando otras solicitudes de manera concurrente. De hecho, en pruebas en producci칩n, este microframework ha podido manejar f치cilmente registros de 40k mientras atiende otras peticiones simult치neamente. Este es el poder de la programaci칩n as칤ncrona en acci칩n.

* Te apetece probarlo?

Animo a todos los backend de PHP a probar esta nueva tecnolog칤a y experimentar los beneficios de la programaci칩n as칤ncrona.

Puedes explorar el c칩digo fuente en  [[https://github.com/pascualmg/cohete][GitHub]]
y conocer m치s sobre mi trabajo en [[https://pascualmg.dev]] , servidor donde se ha puesto en producci칩n este framework para pruebas reales y donde estoy creando un peque침o Portfolio adem치s de ser tambi칠n mi laboratorio de pruebas :)

#PHP #AsyncPHP #Microframework #DDD #DesarrolloWeb #OpenSource #ReactPHP #RxPHP #ReactiveProgramming