version: '3.1'

services:
  db:
    image: mysql:8.0.28
    container_name: reactor-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # replace with your root password
      MYSQL_DATABASE: test  # replace with your database name
      MYSQL_USER: user  # replace with your username
      MYSQL_PASSWORD: userpassword  # replace with your user password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: